name: CI

on:
  push:
    branches:
      - main
    paths:
      - src

jobs:
  check-code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Check types
        run: yarn pnpify tsc --noEmit

      - name: Run unit tests
        run: yarn test
